#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.59.0.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_draw_mandelbrot_impl(
    port_: MessagePort,
    image_size: impl Wire2Api<Size> + UnwindSafe,
    zoom_point: impl Wire2Api<Point> + UnwindSafe,
    scale: impl Wire2Api<f64> + UnwindSafe,
    num_threads: impl Wire2Api<i32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "draw_mandelbrot",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_image_size = image_size.wire2api();
            let api_zoom_point = zoom_point.wire2api();
            let api_scale = scale.wire2api();
            let api_num_threads = num_threads.wire2api();
            move |task_callback| {
                draw_mandelbrot(api_image_size, api_zoom_point, api_scale, api_num_threads)
            }
        },
    )
}
fn wire_passing_complex_structs_impl(
    port_: MessagePort,
    root: impl Wire2Api<TreeNode> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "passing_complex_structs",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_root = root.wire2api();
            move |task_callback| Ok(passing_complex_structs(api_root))
        },
    )
}
fn wire_returning_structs_with_boxed_fields_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "returning_structs_with_boxed_fields",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| Ok(returning_structs_with_boxed_fields()),
    )
}
fn wire_off_topic_memory_test_input_array_impl(
    port_: MessagePort,
    input: impl Wire2Api<Vec<u8>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "off_topic_memory_test_input_array",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_input = input.wire2api();
            move |task_callback| Ok(off_topic_memory_test_input_array(api_input))
        },
    )
}
fn wire_off_topic_memory_test_output_zero_copy_buffer_impl(
    port_: MessagePort,
    len: impl Wire2Api<i32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "off_topic_memory_test_output_zero_copy_buffer",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_len = len.wire2api();
            move |task_callback| Ok(off_topic_memory_test_output_zero_copy_buffer(api_len))
        },
    )
}
fn wire_off_topic_memory_test_output_vec_u8_impl(
    port_: MessagePort,
    len: impl Wire2Api<i32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "off_topic_memory_test_output_vec_u8",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_len = len.wire2api();
            move |task_callback| Ok(off_topic_memory_test_output_vec_u8(api_len))
        },
    )
}
fn wire_off_topic_memory_test_input_vec_of_object_impl(
    port_: MessagePort,
    input: impl Wire2Api<Vec<Size>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "off_topic_memory_test_input_vec_of_object",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_input = input.wire2api();
            move |task_callback| Ok(off_topic_memory_test_input_vec_of_object(api_input))
        },
    )
}
fn wire_off_topic_memory_test_output_vec_of_object_impl(
    port_: MessagePort,
    len: impl Wire2Api<i32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "off_topic_memory_test_output_vec_of_object",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_len = len.wire2api();
            move |task_callback| Ok(off_topic_memory_test_output_vec_of_object(api_len))
        },
    )
}
fn wire_off_topic_memory_test_input_complex_struct_impl(
    port_: MessagePort,
    input: impl Wire2Api<TreeNode> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "off_topic_memory_test_input_complex_struct",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_input = input.wire2api();
            move |task_callback| Ok(off_topic_memory_test_input_complex_struct(api_input))
        },
    )
}
fn wire_off_topic_memory_test_output_complex_struct_impl(
    port_: MessagePort,
    len: impl Wire2Api<i32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "off_topic_memory_test_output_complex_struct",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_len = len.wire2api();
            move |task_callback| Ok(off_topic_memory_test_output_complex_struct(api_len))
        },
    )
}
fn wire_off_topic_deliberately_return_error_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "off_topic_deliberately_return_error",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| off_topic_deliberately_return_error(),
    )
}
fn wire_off_topic_deliberately_panic_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "off_topic_deliberately_panic",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| Ok(off_topic_deliberately_panic()),
    )
}
fn wire_generate_address_from_private_key_impl(
    port_: MessagePort,
    input: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "generate_address_from_private_key",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_input = input.wire2api();
            move |task_callback| Ok(generate_address_from_private_key(api_input))
        },
    )
}
fn wire_sign_message_with_private_key_impl(
    port_: MessagePort,
    msg: impl Wire2Api<String> + UnwindSafe,
    private_key: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "sign_message_with_private_key",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_msg = msg.wire2api();
            let api_private_key = private_key.wire2api();
            move |task_callback| Ok(sign_message_with_private_key(api_msg, api_private_key))
        },
    )
}
fn wire_create_multisig_params_impl(
    port_: MessagePort,
    addresses: impl Wire2Api<Vec<String>> + UnwindSafe,
    threshold: impl Wire2Api<u64> + UnwindSafe,
    unlock_duration: impl Wire2Api<i64> + UnwindSafe,
    start_epoch: impl Wire2Api<i64> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "create_multisig_params",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_addresses = addresses.wire2api();
            let api_threshold = threshold.wire2api();
            let api_unlock_duration = unlock_duration.wire2api();
            let api_start_epoch = start_epoch.wire2api();
            move |task_callback| {
                Ok(create_multisig_params(
                    api_addresses,
                    api_threshold,
                    api_unlock_duration,
                    api_start_epoch,
                ))
            }
        },
    )
}
fn wire_multisig_send_propose_params_impl(
    port_: MessagePort,
    to: impl Wire2Api<String> + UnwindSafe,
    value: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "multisig_send_propose_params",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_to = to.wire2api();
            let api_value = value.wire2api();
            move |task_callback| Ok(multisig_send_propose_params(api_to, api_value))
        },
    )
}
fn wire_multisig_approve_params_impl(port_: MessagePort, txnid: impl Wire2Api<i64> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "multisig_approve_params",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_txnid = txnid.wire2api();
            move |task_callback| Ok(multisig_approve_params(api_txnid))
        },
    )
}
fn wire_message_cid_impl(
    port_: MessagePort,
    from: impl Wire2Api<String> + UnwindSafe,
    to: impl Wire2Api<String> + UnwindSafe,
    nonce: impl Wire2Api<u64> + UnwindSafe,
    value: impl Wire2Api<String> + UnwindSafe,
    method: impl Wire2Api<u64> + UnwindSafe,
    params: impl Wire2Api<String> + UnwindSafe,
    gas_limit: impl Wire2Api<i64> + UnwindSafe,
    gas_fee_cap: impl Wire2Api<String> + UnwindSafe,
    gas_premium: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "message_cid",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_from = from.wire2api();
            let api_to = to.wire2api();
            let api_nonce = nonce.wire2api();
            let api_value = value.wire2api();
            let api_method = method.wire2api();
            let api_params = params.wire2api();
            let api_gas_limit = gas_limit.wire2api();
            let api_gas_fee_cap = gas_fee_cap.wire2api();
            let api_gas_premium = gas_premium.wire2api();
            move |task_callback| {
                Ok(message_cid(
                    api_from,
                    api_to,
                    api_nonce,
                    api_value,
                    api_method,
                    api_params,
                    api_gas_limit,
                    api_gas_fee_cap,
                    api_gas_premium,
                ))
            }
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<f64> for f64 {
    fn wire2api(self) -> f64 {
        self
    }
}
impl Wire2Api<i32> for i32 {
    fn wire2api(self) -> i32 {
        self
    }
}
impl Wire2Api<i64> for i64 {
    fn wire2api(self) -> i64 {
        self
    }
}

impl Wire2Api<u64> for u64 {
    fn wire2api(self) -> u64 {
        self
    }
}
impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

impl support::IntoDart for BoxedPoint {
    fn into_dart(self) -> support::DartAbi {
        vec![(*self.point).into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for BoxedPoint {}

impl support::IntoDart for Point {
    fn into_dart(self) -> support::DartAbi {
        vec![self.x.into_dart(), self.y.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for Point {}

impl support::IntoDart for Size {
    fn into_dart(self) -> support::DartAbi {
        vec![self.width.into_dart(), self.height.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for Size {}

impl support::IntoDart for TreeNode {
    fn into_dart(self) -> support::DartAbi {
        vec![self.name.into_dart(), self.children.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for TreeNode {}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
#[path = "bridge_generated.web.rs"]
mod web;
#[cfg(target_family = "wasm")]
pub use web::*;

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
