// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.59.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import "bridge_definitions.dart";
import 'dart:convert';
import 'dart:async';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';

import 'package:meta/meta.dart';

class FlutterRustBridgeExampleImpl implements FlutterRustBridgeExample {
  final FlutterRustBridgeExamplePlatform _platform;
  factory FlutterRustBridgeExampleImpl(ExternalLibrary dylib) =>
      FlutterRustBridgeExampleImpl.raw(FlutterRustBridgeExamplePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory FlutterRustBridgeExampleImpl.wasm(FutureOr<WasmModule> module) =>
      FlutterRustBridgeExampleImpl(module as ExternalLibrary);
  FlutterRustBridgeExampleImpl.raw(this._platform);
  Future<Uint8List> drawMandelbrot(
      {required Size imageSize,
      required Point zoomPoint,
      required double scale,
      required int numThreads,
      dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_size(imageSize);
    var arg1 = _platform.api2wire_box_autoadd_point(zoomPoint);
    var arg2 = api2wire_f64(scale);
    var arg3 = api2wire_i32(numThreads);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_draw_mandelbrot(port_, arg0, arg1, arg2, arg3),
      parseSuccessData: _wire2api_ZeroCopyBuffer_Uint8List,
      constMeta: kDrawMandelbrotConstMeta,
      argValues: [imageSize, zoomPoint, scale, numThreads],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kDrawMandelbrotConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "draw_mandelbrot",
        argNames: ["imageSize", "zoomPoint", "scale", "numThreads"],
      );

  Future<String> passingComplexStructs({required TreeNode root, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_tree_node(root);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_passing_complex_structs(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kPassingComplexStructsConstMeta,
      argValues: [root],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kPassingComplexStructsConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "passing_complex_structs",
        argNames: ["root"],
      );

  Future<BoxedPoint> returningStructsWithBoxedFields({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_returning_structs_with_boxed_fields(port_),
      parseSuccessData: _wire2api_boxed_point,
      constMeta: kReturningStructsWithBoxedFieldsConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta
      get kReturningStructsWithBoxedFieldsConstMeta =>
          const FlutterRustBridgeTaskConstMeta(
            debugName: "returning_structs_with_boxed_fields",
            argNames: [],
          );

  Future<int> offTopicMemoryTestInputArray(
      {required Uint8List input, dynamic hint}) {
    var arg0 = _platform.api2wire_uint_8_list(input);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_off_topic_memory_test_input_array(port_, arg0),
      parseSuccessData: _wire2api_i32,
      constMeta: kOffTopicMemoryTestInputArrayConstMeta,
      argValues: [input],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kOffTopicMemoryTestInputArrayConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "off_topic_memory_test_input_array",
        argNames: ["input"],
      );

  Future<Uint8List> offTopicMemoryTestOutputZeroCopyBuffer(
      {required int len, dynamic hint}) {
    var arg0 = api2wire_i32(len);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_off_topic_memory_test_output_zero_copy_buffer(port_, arg0),
      parseSuccessData: _wire2api_ZeroCopyBuffer_Uint8List,
      constMeta: kOffTopicMemoryTestOutputZeroCopyBufferConstMeta,
      argValues: [len],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta
      get kOffTopicMemoryTestOutputZeroCopyBufferConstMeta =>
          const FlutterRustBridgeTaskConstMeta(
            debugName: "off_topic_memory_test_output_zero_copy_buffer",
            argNames: ["len"],
          );

  Future<Uint8List> offTopicMemoryTestOutputVecU8(
      {required int len, dynamic hint}) {
    var arg0 = api2wire_i32(len);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_off_topic_memory_test_output_vec_u8(port_, arg0),
      parseSuccessData: _wire2api_uint_8_list,
      constMeta: kOffTopicMemoryTestOutputVecU8ConstMeta,
      argValues: [len],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kOffTopicMemoryTestOutputVecU8ConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "off_topic_memory_test_output_vec_u8",
        argNames: ["len"],
      );

  Future<int> offTopicMemoryTestInputVecOfObject(
      {required List<Size> input, dynamic hint}) {
    var arg0 = _platform.api2wire_list_size(input);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_off_topic_memory_test_input_vec_of_object(port_, arg0),
      parseSuccessData: _wire2api_i32,
      constMeta: kOffTopicMemoryTestInputVecOfObjectConstMeta,
      argValues: [input],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta
      get kOffTopicMemoryTestInputVecOfObjectConstMeta =>
          const FlutterRustBridgeTaskConstMeta(
            debugName: "off_topic_memory_test_input_vec_of_object",
            argNames: ["input"],
          );

  Future<List<Size>> offTopicMemoryTestOutputVecOfObject(
      {required int len, dynamic hint}) {
    var arg0 = api2wire_i32(len);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_off_topic_memory_test_output_vec_of_object(port_, arg0),
      parseSuccessData: _wire2api_list_size,
      constMeta: kOffTopicMemoryTestOutputVecOfObjectConstMeta,
      argValues: [len],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta
      get kOffTopicMemoryTestOutputVecOfObjectConstMeta =>
          const FlutterRustBridgeTaskConstMeta(
            debugName: "off_topic_memory_test_output_vec_of_object",
            argNames: ["len"],
          );

  Future<int> offTopicMemoryTestInputComplexStruct(
      {required TreeNode input, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_tree_node(input);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_off_topic_memory_test_input_complex_struct(port_, arg0),
      parseSuccessData: _wire2api_i32,
      constMeta: kOffTopicMemoryTestInputComplexStructConstMeta,
      argValues: [input],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta
      get kOffTopicMemoryTestInputComplexStructConstMeta =>
          const FlutterRustBridgeTaskConstMeta(
            debugName: "off_topic_memory_test_input_complex_struct",
            argNames: ["input"],
          );

  Future<TreeNode> offTopicMemoryTestOutputComplexStruct(
      {required int len, dynamic hint}) {
    var arg0 = api2wire_i32(len);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_off_topic_memory_test_output_complex_struct(port_, arg0),
      parseSuccessData: _wire2api_tree_node,
      constMeta: kOffTopicMemoryTestOutputComplexStructConstMeta,
      argValues: [len],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta
      get kOffTopicMemoryTestOutputComplexStructConstMeta =>
          const FlutterRustBridgeTaskConstMeta(
            debugName: "off_topic_memory_test_output_complex_struct",
            argNames: ["len"],
          );

  Future<int> offTopicDeliberatelyReturnError({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_off_topic_deliberately_return_error(port_),
      parseSuccessData: _wire2api_i32,
      constMeta: kOffTopicDeliberatelyReturnErrorConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta
      get kOffTopicDeliberatelyReturnErrorConstMeta =>
          const FlutterRustBridgeTaskConstMeta(
            debugName: "off_topic_deliberately_return_error",
            argNames: [],
          );

  Future<int> offTopicDeliberatelyPanic({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_off_topic_deliberately_panic(port_),
      parseSuccessData: _wire2api_i32,
      constMeta: kOffTopicDeliberatelyPanicConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kOffTopicDeliberatelyPanicConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "off_topic_deliberately_panic",
        argNames: [],
      );

  Future<String> generateAddressFromPrivateKey(
      {required String input, dynamic hint}) {
    var arg0 = _platform.api2wire_String(input);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_generate_address_from_private_key(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kGenerateAddressFromPrivateKeyConstMeta,
      argValues: [input],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGenerateAddressFromPrivateKeyConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "generate_address_from_private_key",
        argNames: ["input"],
      );

  Future<StringArray2> signMessageWithPrivateKey(
      {required String msg, required String privateKey, dynamic hint}) {
    var arg0 = _platform.api2wire_String(msg);
    var arg1 = _platform.api2wire_String(privateKey);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_sign_message_with_private_key(port_, arg0, arg1),
      parseSuccessData: _wire2api_String_array_2,
      constMeta: kSignMessageWithPrivateKeyConstMeta,
      argValues: [msg, privateKey],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSignMessageWithPrivateKeyConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "sign_message_with_private_key",
        argNames: ["msg", "privateKey"],
      );

  Future<String> createMultisigParams(
      {required List<String> addresses,
      required int threshold,
      required int unlockDuration,
      required int startEpoch,
      dynamic hint}) {
    var arg0 = _platform.api2wire_StringList(addresses);
    var arg1 = _platform.api2wire_u64(threshold);
    var arg2 = _platform.api2wire_i64(unlockDuration);
    var arg3 = _platform.api2wire_i64(startEpoch);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_create_multisig_params(port_, arg0, arg1, arg2, arg3),
      parseSuccessData: _wire2api_String,
      constMeta: kCreateMultisigParamsConstMeta,
      argValues: [addresses, threshold, unlockDuration, startEpoch],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kCreateMultisigParamsConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "create_multisig_params",
        argNames: ["addresses", "threshold", "unlockDuration", "startEpoch"],
      );

  Future<String> multisigSendProposeParams(
      {required String to, required String value, dynamic hint}) {
    var arg0 = _platform.api2wire_String(to);
    var arg1 = _platform.api2wire_String(value);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_multisig_send_propose_params(port_, arg0, arg1),
      parseSuccessData: _wire2api_String,
      constMeta: kMultisigSendProposeParamsConstMeta,
      argValues: [to, value],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kMultisigSendProposeParamsConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "multisig_send_propose_params",
        argNames: ["to", "value"],
      );

  Future<String> multisigApproveParams({required int txnid, dynamic hint}) {
    var arg0 = _platform.api2wire_i64(txnid);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_multisig_approve_params(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kMultisigApproveParamsConstMeta,
      argValues: [txnid],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kMultisigApproveParamsConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "multisig_approve_params",
        argNames: ["txnid"],
      );

  Future<String> messageCid(
      {required String from,
      required String to,
      required int nonce,
      required String value,
      required int method,
      required String params,
      required int gasLimit,
      required String gasFeeCap,
      required String gasPremium,
      dynamic hint}) {
    var arg0 = _platform.api2wire_String(from);
    var arg1 = _platform.api2wire_String(to);
    var arg2 = _platform.api2wire_u64(nonce);
    var arg3 = _platform.api2wire_String(value);
    var arg4 = _platform.api2wire_u64(method);
    var arg5 = _platform.api2wire_String(params);
    var arg6 = _platform.api2wire_i64(gasLimit);
    var arg7 = _platform.api2wire_String(gasFeeCap);
    var arg8 = _platform.api2wire_String(gasPremium);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_message_cid(
          port_, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8),
      parseSuccessData: _wire2api_String,
      constMeta: kMessageCidConstMeta,
      argValues: [
        from,
        to,
        nonce,
        value,
        method,
        params,
        gasLimit,
        gasFeeCap,
        gasPremium
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kMessageCidConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "message_cid",
        argNames: [
          "from",
          "to",
          "nonce",
          "value",
          "method",
          "params",
          "gasLimit",
          "gasFeeCap",
          "gasPremium"
        ],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  StringArray2 _wire2api_String_array_2(dynamic raw) {
    return StringArray2((raw as List<dynamic>).map(_wire2api_String).toList());
  }

  Uint8List _wire2api_ZeroCopyBuffer_Uint8List(dynamic raw) {
    return raw as Uint8List;
  }

  Point _wire2api_box_point(dynamic raw) {
    return _wire2api_point(raw);
  }

  BoxedPoint _wire2api_boxed_point(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return BoxedPoint(
      point: _wire2api_box_point(arr[0]),
    );
  }

  double _wire2api_f64(dynamic raw) {
    return raw as double;
  }

  int _wire2api_i32(dynamic raw) {
    return raw as int;
  }

  List<String> _wire2api_list_String(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_String).toList();
  }

  List<Size> _wire2api_list_size(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_size).toList();
  }

  List<TreeNode> _wire2api_list_tree_node(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_tree_node).toList();
  }

  Point _wire2api_point(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Point(
      x: _wire2api_f64(arr[0]),
      y: _wire2api_f64(arr[1]),
    );
  }

  Size _wire2api_size(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Size(
      width: _wire2api_i32(arr[0]),
      height: _wire2api_i32(arr[1]),
    );
  }

  TreeNode _wire2api_tree_node(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TreeNode(
      name: _wire2api_String(arr[0]),
      children: _wire2api_list_tree_node(arr[1]),
    );
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }
}

// Section: api2wire

@protected
double api2wire_f64(double raw) {
  return raw;
}

@protected
int api2wire_i32(int raw) {
  return raw;
}

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer
